(bup/bown) add usage and error catch

diff --git a/bin/bown b/bin/bown
--- a/bin/bown
+++ b/bin/bown
@@ -1,7 +1,11 @@
 #!/usr/bin/env bash
 
 # Simple script to use brightnessctl up by given percentage
+# Usage: bown <number>
 
 amount=$1
 
-brightnessctl set "${amount}%-" &>/dev/null
+if ! brightnessctl set "${amount}%-" &>/dev/null; then
+	echo "Unable to change brigntness via brightnessctl"
+	exit 1
+fi
diff --git a/bin/bup b/bin/bup
--- a/bin/bup
+++ b/bin/bup
@@ -1,7 +1,11 @@
 #!/usr/bin/env bash
 
 # Simple script to use brightnessctl up by given percentage
+# Usage: bup <number>
 
 amount=$1
 
-brightnessctl set "+${amount}%" 1>/dev/null
+if ! brightnessctl set "+${amount}%" 1>/dev/null; then
+	echo "Unable to change brigntness via brightnessctl"
+	exit 1
+fi
